### ISSUE TITLE
Pip install from github does not work

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/EvoSim#31]
> (test_env) Dunbar ~/projects :) pip install git+https://github.com/ImperialCollegeLondon/EvoSim.git@main
> Collecting git+https://github.com/ImperialCollegeLondon/EvoSim.git@main
>   Cloning https://github.com/ImperialCollegeLondon/EvoSim.git (to revision main) to /tmp/pip-req-build-_n_7dbx_
> Username for 'https://github.com': cc-a
> Password for 'https://cc-a@github.com': 
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>     Preparing wheel metadata ... done
> Building wheels for collected packages: poetry-template
>   Building wheel for poetry-template (PEP 517) ... done
>   Created wheel for poetry-template: filename=poetry_template-0.1.0-py3-none-any.whl size=3257 sha256=244ca082159359fc4a7bb21b6521be7a990097f3926d101ebfd40bae539ff8c1
>   Stored in directory: /tmp/pip-ephem-wheel-cache-sd37avp7/wheels/67/fb/f4/43ca3eb9e490ec4ec5f3a624f4ec6ec01134cd9687089f1833
> Successfully built poetry-template
> Installing collected packages: poetry-template
> Successfully installed poetry-template-0.1.0
> WARNING: You are using pip version 20.2.1; however, version 20.2.3 is available.
> You should consider upgrading via the '/home/ccaveayl/projects/test_env/bin/python -m pip install --upgrade pip' command.
> (test_env) Dunbar ~/projects :) python
> Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
> [GCC 10.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> \>>> import evosim
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'evosim'
> \>>> 
>

**Comment by mdavezac** [comment]
Can't reproduce. Might work since merging #2.

**Comment by cc-a** [comment]
Indeed seems to be working now.
